name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # 別のブランチ名（masterなど）を使っている場合は書き換えてください

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
